spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_app_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
